name: Transporter
main: com.frdfsnlght.transporter.Transporter
version: "8.16"
authors:
  - frdfsnlght
website: https://github.com/frdfsnlght/Transporter/
description: >
  Provides teleportation through gates between worlds and servers.
softdepend: [Vault, Inquisitor, Permissions, PermissionsEx, Register, Dynmap, TabAPI, VanishNoPacket]
commands:
  trp:
    description: Main Transporter command. See /trp help for more.
    usage: /<command> command [<option> ...]
